//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracKiralamaOtomasyonuEntities : DbContext
    {
        public AracKiralamaOtomasyonuEntities()
            : base("name=AracKiralamaOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aracKira> aracKira { get; set; }
        public virtual DbSet<aracList> aracList { get; set; }
        public virtual DbSet<aracMarka> aracMarka { get; set; }
        public virtual DbSet<userList> userList { get; set; }
        public virtual DbSet<userRolList> userRolList { get; set; }
        public virtual DbSet<userSession> userSession { get; set; }
    }
}
