//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class aracList
    {
        public string aracPlaka { get; set; }
        public string aracResim { get; set; }
        public int aracMarkaID { get; set; }
        public string aracAdi { get; set; }
        public string aracRenk { get; set; }
        public string aracYakitTipi { get; set; }
        public string aracVitesTipi { get; set; }
        public string aracBavulSayisi { get; set; }
        public string aracKoltukSayisi { get; set; }
        public bool aracKlimali { get; set; }
        public bool aracAktif { get; set; }
    
        public virtual aracMarka aracMarka { get; set; }
    }
}
