//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class userList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userList()
        {
            this.userSession = new HashSet<userSession>();
        }
    
        public string userTC { get; set; }
        public string userLogin { get; set; }
        public string userPass { get; set; }
        public string userAd { get; set; }
        public string userSoyad { get; set; }
        public string userCinsiyet { get; set; }
        public string userEPosta { get; set; }
        public string userTel { get; set; }
        public System.DateTime userDtarihi { get; set; }
        public string userDyeri { get; set; }
        public string userAvatar { get; set; }
        public int rolID { get; set; }
        public bool userAktif { get; set; }
    
        public virtual userRolList userRolList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userSession> userSession { get; set; }
    }
}
