//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralamaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class userSession
    {
        public string sessionKey { get; set; }
        public string userTC { get; set; }
        public System.DateTime sessionTarih { get; set; }
        public bool sessionAktif { get; set; }
    
        public virtual userList userList { get; set; }
    }
}
